function buat_login() {
  var elem = document.getElementById("X");
  elem.parentElement.removeChild(elem);
  var p = document.createElement("p");
  p.className = "tulisan_login";
  p.innerHTML = "SILAHKAN MENDAFTAR";
  var element = document.getElementsByTagName("div")[0];
  element.appendChild(p);
  var form = document.createElement("form");
  element.appendChild(form);
  var label = document.createElement("label");
  label.innerHTML = "Nama User";
  form.appendChild(label);
  var user = document.createElement("input");
  user.type = "text";
  user.name = "user";
  user.placeholder = "Nama User..";
  user.className = "form_login";
  form.appendChild(user);
  var label2 = document.createElement("label");
  label2.innerHTML = "Nomor Handphone";
  form.appendChild(label2);
  var no_hp = document.createElement("input");
  no_hp.type = "text";
  no_hp.name = "no_hp";
  no_hp.placeholder = "No Handphone..";
  no_hp.className = "form_login";
  form.appendChild(no_hp);
  var label3 = document.createElement("label");
  label3.innerHTML = "Username";
  form.appendChild(label3);
  var username = document.createElement("input");
  username.type = "text";
  username.name = "username";
  username.placeholder = "Username atau email..";
  username.className = "form_login";
  form.appendChild(username);
  var label4 = document.createElement("label");
  label4.innerHTML = "Password";
  form.appendChild(label4);
  var password = document.createElement("input");
  password.type = "password";
  password.name = "password";
  password.placeholder = "Password..";
  password.className = "form_login";
  form.appendChild(password);
  var tombol = document.createElement("input");
  tombol.type = "submit";
  tombol.value = "DAFTAR SEKARANG";
  tombol.className = "tombol_login";
  form.appendChild(tombol);
}
